---
- name: Install Minishift and its dependencies
  hosts: all
  user: root
  become: yes
  tasks:
    - name: Install KVM driver
      get_url:
        url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm
        dest: /usr/local/bin/docker-machine-driver-kvm
        mode: 0755

    - name: Install dependencies
      dnf: name={{ item }} state=present
      with_items:
        - qemu-kvm
        - libvirt

    - name: Get Minishift from Github
      get_url:
        url: https://github.com/minishift/minishift/releases/download/v1.0.0-beta.4/minishift-1.0.0-beta.4-linux-amd64.tgz
        dest: /tmp
        mode: 0755

    - name: Unarchive Minishift
      unarchive:
        src: /tmp/minishift-1.0.0-beta.4-linux-amd64.tgz
        dest: /usr/local/bin

    - name: Get origin-client from source
      get_url:
        url: https://github.com/openshift/origin/releases/download/v1.5.0-alpha.3/openshift-origin-client-tools-v1.5.0-alpha.3-cf7e336-linux-64bit.tar.gz
        dest: /tmp
        mode: 0755

    - name: Install origin-client
      unarchive:
        src: /tmp/openshift-origin-client-tools-v1.5.0-alpha.3-cf7e336-linux-64bit.tar.gz
        dest: /usr/local/bin
