---
- name: Start Minishift
  hosts: all
  user: root
  vars_files:
    - external_vars.yml
  tasks:
    - name: Start Minishift
      command: minishift start
      environment:
        MINISHIFT_GITHUB_API_TOKEN: "{{ github_api_token }}"

    - name: Login as system:admin
      command: oc login -u system:admin
